---
version: 1.9-beta3
slug: hp-airpint
name: HP Airprint Server
description: Enhance your old HP Printer to support AirPrint
url: https://github.com/madmuffin1/homeassistant-cups-hp-airprint
codenotary: patrick.brueckner87@gmail.com
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
hassio_api: true
host_network: true
map:
  - data:rw
  - share:rw
init: false
ports:
  631/tcp: 631
ports_description:
  631/tcp: CUPS web interface and printing port
options:
  admin_username: "admin"
  admin_password: "admin"
schema:
  admin_username: str
  admin_password: password
startup: services
usb: true
dbus: true
apparmor: true
ingress: true
ingress_port: 631
